server:
  port: 80

# Zookeeper 配置
zookeeper:
  host: 122.112.235.38
  port: 2181
  timeout: 60000
  rootPath: /any/db
  username: ScheduleAdmin
  password: password

# 数据库 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qiuqiu?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: s.china
    sql-script-encoding: utf-8

# Mybatis 配置
mybatis:
  config-location: classpath:/mybatis.xml





